version: 2
jobs:
  build:

    working_directory: ~/akkaserverless-wirelessmesh-java

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: akkaserverless-wirelessmesh-java-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/akkaserverless-wirelessmesh-java-1.0-SNAPSHOT.jar
